export interface TramStop {
  line: string;
  stops: string[];
}

export const tramStops: TramStop[] = [
  {
    line: 'M1',
    stops: [
      'Schillerstr.',
      'Waldemarstr.',
      'Nordend',
      'Heinrich-Böll-Str.',
      'Kuckhoffstr.',
      'Hermann-Hesse-Str./Waldstr.',
      'Rosenthal Nord',
      'Hauptstr./Friedrich-Engels-Str.',
      'Wiesenwinkel',
      'Angerweg',
      'Nordendstr.',
      'Friedrich-Engels-Str./Eichenstr.',
      'Am Iderfenngraben',
      'Pastor-Niemöller-Platz',
      'Grabbeallee/Pastor-Niemöller-Pl.',
      'Tschaikowskistr.',
      'Bürgerpark Pankow',
      'Rathaus Pankow',
      'Pankow Kirche',
      'S+U Pankow',
      'Masurenstr.',
      'U Vinetastr.',
      'Schönhauser Allee/Bornholmer Str',
      'S+U Schönhauser Allee',
      'Milastr.',
      'U Eberswalder Str.',
      'Schwedter Str.',
      'Zionskirchplatz',
      'U Rosenthaler Platz',
      'U Weinmeisterstr./Gipsstr.',
      'S Hackescher Markt',
      'Monbijouplatz',
      'S Oranienburger Str.',
      'U Oranienburger Tor',
      'U Oranienburger Tor',
      'S+U Friedrichstr.',
      'Universitätsstr.',
      'Georgenstr./Am Kupfergraben',
      'Am Kupfergraben'
    ]
  },
  {
    line: 'M2',
    stops: [
      'Heinersdorf',
      'Rothenbachstr.',
      'Heinersdorf Kirche',
      'Am Wasserturm',
      'Tino-Schwierzina-Str.',
      'Am Steinberg',
      'Prenzlauer Prom./Am Steinberg',
      'Prenzlauer Allee/Ostseestr.',
      'Erich-Weinert-Str.',
      'S Prenzlauer Allee',
      'Fröbelstr.',
      'Prenzlauer Allee/Danziger Str.',
      'Marienburger Str.',
      'Knaackstr.',
      'Prenzlauer Allee/Metzer Str.',
      'Mollstr./Prenzlauer Allee',
      'S+U Alexanderpl/Memhardstr.',
      'S+U Alexanderplatz/Dircksenstr.'
    ]
  },
  {
    line: 'M4',
    stops: [
      'Falkenberg',
      'Welsestr.',
      'Falkenberger Ch./Prendener Str.',
      'S Hohenschönhausen',
      'Zingster Str.',
      'Zingster Str./Ribnitzer Str.',
      'Ahrenshooper Str.',
      'Prerower Platz',
      'Hansastr./Malchower Weg',
      'Feldtmannstr.',
      'Stadion Buschallee/Hansastr.',
      'Giersstr.',
      'Hansastr./Buschallee',
      'Sulzfelder Str.',
      'Buschallee',
      'Weißer See',
      'Albertinenstr.',
      'Antonplatz',
      'Greifswalder Str./Ostseestr.',
      'Thomas-Mann-Str.',
      'S Greifswalder Str.',
      'Greifswalder Str./Danziger Str.',
      'Hufelandstr.',
      'Am Friedrichshain',
      'Mollstr./Otto-Braun-Str.',
      'U Alexanderplatz',
      'S+U Alexanderplatz/Gontardstr.',
      'Spandauer Str./Marienkirche',
      'S Hackescher Markt'
    ]
  },
  {
    line: 'M5',
    stops: [
      'Zingster Str.',
      'Zingster Str./Ribnitzer Str.',
      'Ahrenshooper Str.',
      'Prerower Platz',
      'Rüdickenstr.',
      'Arnimstr.',
      'Anna-Ebermann-Str.',
      'Gehrenseestr.',
      'Alt-Hohenschönhausen',
      'Oberseestr.',
      'Freienwalder Str.',
      'Werneuchener Str.',
      'Simon-Bolivar-Str.',
      'Sandinostr.',
      'Hohenschönhauser Str.',
      'Judith-Auer-Str.',
      'Oderbruchstr.',
      'S Landsberger Allee',
      'Landsberger Al./Petersburger Str',
      'Klinikum im Friedrichshain',
      'Platz der Vereinten Nationen',
      'Büschingstr.',
      'Mollstr./Otto-Braun-Str.',
      'U Alexanderplatz',
      'S+U Alexanderplatz/Gontardstr.',
      'Spandauer Str./Marienkirche',
      'S Hackescher Markt',
      'Monbijouplatz',
      'S Oranienburger Str.',
      'U Oranienburger Tor',
      'Torstr./U Oranienburger Tor',
      'U Naturkundemuseum',
      'U Naturkundemuseum',
      'Invalidenpark',
      'S+U Hauptbahnhof',
      'Clara-Jaschke-Str.',
      'Lesser-Ury-Weg',
      'Lüneburger Str.'
    ]
  },
  {
    line: 'M6',
    stops: [
      'Riesaer Str.',
      'Riesaer Str./Louis-Lewin-Str.',
      'Jenaer Str.',
      'Nossener Str.',
      'U Hellersdorf',
      'Stendaler Str./Quedlinburger Str',
      'Stendaler Str./Zossener Str.',
      'Zossener Str./Kastanienallee',
      'Alte Hellersdorfer/Zossener Str.',
      'Michendorfer Str.',
      'Landsberger Ch./Zossener Str.',
      'Betriebshof Marzahn',
      'Brodowiner Ring',
      'Landsberger Allee/Blumberger D.',
      'Jan-Petersen-Str.',
      'Freizeitforum Marzahn',
      'Marzahner Promenade',
      'S Marzahn',
      'Gewerbepark Georg Knorr',
      'Dingelstädter Str.',
      'Landsberger Allee/Rhinstr.',
      'Schalkauer Str.',
      'Arendsweg',
      'Genslerstr.',
      'Zechliner Str.',
      'Altenhofer Str.',
      'Hohenschönhauser Str.',
      'Judith-Auer-Str.',
      'Oderbruchstr.',
      'S Landsberger Allee',
      'Landsberger Al./Petersburger Str',
      'Klinikum im Friedrichshain',
      'Platz der Vereinten Nationen',
      'Büschingstr.',
      'Mollstr./Otto-Braun-Str.',
      'U Alexanderplatz',
      'S+U Alexanderplatz/Gontardstr.',
      'Spandauer Str./Marienkirche',
      'S Hackescher Markt'
    ]
  },
  {
    line: 'M8',
    stops: [
      'Ahrensfelde/Stadtgrenze',
      'Barnimplatz',
      'Niemegker Str.',
      'Wuhletalstr.',
      'Max-Herrmann-Str.',
      'Bürgerpark Marzahn',
      'Jan-Petersen-Str.',
      'Alt-Marzahn',
      'Adersleber Weg',
      'Allee d. Kosmonauten/Poelchaustr',
      'Boschpoler Str.',
      'Helene-Weigel-Platz',
      'S Springpfuhl',
      'Beilsteiner Str.',
      'Allee der Kosmonauten/Rhinstr.',
      'Ev. Krankenhaus KEH',
      'Herzbergstr./Siegfriedstr.',
      'Herzbergstr./Industriegebiet',
      'Bernhard-Bästlein-Str.',
      'Roederplatz',
      'Anton-Saefkow-Platz',
      'Landsberger Allee/Karl-Lade-Str.',
      'S Landsberger Allee',
      'Landsberger Al./Petersburger Str',
      'Klinikum im Friedrichshain',
      'Platz der Vereinten Nationen',
      'Büschingstr.',
      'Mollstr./Otto-Braun-Str.',
      'Mollstr./Prenzlauer Allee',
      'U Rosa-Luxemburg-Platz',
      'U Rosenthaler Platz',
      'Brunnenstr./Invalidenstr.',
      'Pappelplatz',
      'S Nordbahnhof',
      'U Naturkundemuseum',
      'Invalidenpark',
      'S+U Hauptbahnhof',
      'Clara-Jaschke-Str.',
      'Lesser-Ury-Weg',
      'Lüneburger Str.'
    ]
  },
  {
    line: 'M10',
    stops: [
      'Lüneburger Str.',
      'Lesser-Ury-Weg',
      'Clara-Jaschke-Str.',
      'S+U Hauptbahnhof',
      'Invalidenpark',
      'U Naturkundemuseum',
      'S Nordbahnhof',
      'Gedenkstätte Berliner Mauer',
      'U Bernauer Str.',
      'Wolliner Str.',
      'Friedrich-Ludwig-Jahn-Sportpark',
      'U Eberswalder Str.',
      'Husemannstr.',
      'Prenzlauer Allee/Danziger Str.',
      'Winsstr.',
      'Greifswalder Str./Danziger Str.',
      'Arnswalder Platz',
      'Kniprodestr./Danziger Str.',
      'Paul-Heyse-Str.',
      'Landsberger All./Petersburger Str.',
      'Straßmannstr.',
      'Bersarinplatz',
      'U Frankfurter Tor',
      'Grünberger Str./Warschauer Str.',
      'Revaler Str.',
      'S Warschauer Str.',
      'S+U Warschauer Str.'
    ]
  },
  {
    line: 'M13',
    stops: [
      'Virchow-Klinikum',
      'Seestr./Amrumer Str.',
      'U Seestr.',
      'Osram-Höfe',
      'Louise-Schroeder-Platz',
      'U Osloer Str.',
      'Drontheimer Str.',
      'Osloer Str./Prinzenallee',
      'Grüntaler Str.',
      'S Bornholmer Str.',
      'Björnsonstr.',
      'Schönfließer Str.',
      'Schönhauser Allee/Bornholmer Str',
      'Stahlheimer Str./Wisbyer Str.',
      'Prenzlauer Allee/Ostseestr.',
      'Gustav-Adolf-Str./Langhansstr.',
      'Friesickestr.',
      'Behaimstr.',
      'Antonplatz',
      'Albertinenstr.',
      'Weißer See',
      'Gounodstr.',
      'Betriebshof Indira-Gandhi-Str.',
      'Sportforum',
      'Hohenschönhauser Str.',
      'Landsberger Allee/Weißenseer W.',
      'Roederplatz',
      'Möllendorffstr./Storkower Str.',
      'Loeperplatz',
      'Rathaus Lichtenberg',
      'S+U Frankfurter Allee',
      'Scharnweberstr./Weichselstr.',
      'Boxhagener Str./Holteistr.',
      'Wühlischstr./Gärtnerstr.',
      'Simplonstr.',
      'Libauer Str.',
      'Kopernikusstr./Warschauer Str.',
      'S Warschauer Str.',
      'Revaler Str.'
    ]
  },
  {
    line: 'M17',
    stops: [
      'Falkenberg',
      'Welsestr.',
      'Falkenberger Ch./Prendener Str.',
      'S Hohenschönhausen',
      'Prerower Platz',
      'Rüdickenstr.',
      'Arnimstr.',
      'Anna-Ebermann-Str.',
      'Gehrenseestr.',
      'Rhinstr./Gärtnerstr.',
      'Rhinstr./Plauener Str.',
      'Landsberger Allee/Rhinstr.',
      'Meeraner Str.',
      'Allee der Kosmonauten/Rhinstr.',
      'Kleingartenanlage Bielefeldt',
      'S Friedrichsfelde Ost',
      'Alt-Friedrichsfelde/Rhinstr.',
      'Am Tierpark/Alfred-Kowalke-Str.',
      'Criegernweg',
      'U Tierpark',
      'Treskowallee/HTW',
      'Marksburgstr.',
      'S Karlshorst',
      'S Karlshorst/Wandlitzstr.',
      'Treskowallee/ Ehrlichstr.',
      'Hegemeisterweg',
      'Treskowallee/Volkspark Wuhlheide',
      'Rummelsburger Str./Edisonstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Brückenstr.',
      'S Schöneweide',
      'S Schöneweide/Sterndamm'
    ]
  },
  {
    line: '12',
    stops: [
      'Pasedagplatz',
      'Berliner Allee/Rennbahnstr.',
      'Falkenberger Str./Berliner Allee',
      'Weißer See',
      'Albertinenstr.',
      'Antonplatz',
      'Behaimstr.',
      'Friesickestr.',
      'Gustav-Adolf-Str./Langhansstr.',
      'Prenzlauer Allee/Ostseestr.',
      'Stahlheimer Str./Wisbyer Str.',
      'Humannplatz',
      'Stargarder Str.',
      'Raumerstr.',
      'U Eberswalder Str./Pappelallee',
      'U Eberswalder Str.',
      'Schwedter Str.',
      'Zionskirchplatz',
      'Brunnenstr./Invalidenstr.',
      'Pappelplatz',
      'S Nordbahnhof',
      'U Naturkundemuseum',
      'Torstr./U Oranienburger Tor',
      'U Oranienburger Tor',
      'S+U Friedrichstr.',
      'Universitätsstr.',
      'Georgenstr./Am Kupfergraben',
      'Am Kupfergraben'
    ]
  },
  {
    line: '16',
    stops: [
      'Ahrensfelde/Stadtgrenze',
      'Barnimplatz',
      'Niemegker Str.',
      'Wuhletalstr.',
      'Max-Herrmann-Str.',
      'Bürgerpark Marzahn',
      'Freizeitforum Marzahn',
      'Marzahner Promenade',
      'S Marzahn',
      'Gewerbepark Georg Knorr',
      'Dingelstädter Str.',
      'Landsberger Allee/Rhinstr.',
      'Schalkauer Str.',
      'Arendsweg',
      'Genslerstr.',
      'Zechliner Str.',
      'Altenhofer Str.',
      'Hohenschönhauser Str.',
      'Landsberger Allee/Weißenseer W.',
      'Roederplatz',
      'Möllendorffstr./Storkower Str.',
      'Loeperplatz',
      'Rathaus Lichtenberg',
      'S+U Frankfurter Allee',
      'Scharnweberstr./Weichselstr.'
    ]
  },
  {
    line: '18',
    stops: [
      'Riesaer Str.',
      'Riesaer Str./Louis-Lewin-Str.',
      'Jenaer Str.',
      'Nossener Str.',
      'U Hellersdorf',
      'Stendaler Str./Quedlinburger Str',
      'Stendaler Str./Zossener Str.',
      'Zossener Str./Kastanienallee',
      'Alte Hellersdorfer/Zossener Str.',
      'Michendorfer Str.',
      'Landsberger Ch./Zossener Str.',
      'Betriebshof Marzahn',
      'Brodowiner Ring',
      'Landsberger Allee/Blumberger D.',
      'Alt-Marzahn',
      'Adersleber Weg',
      'Allee d. Kosmonauten/Poelchaustr',
      'Boschpoler Str.',
      'Helene-Weigel-Platz',
      'S Springpfuhl'
    ]
  },
  {
    line: '21',
    stops: [
      'S+U Lichtenberg/Gudrunstr.',
      'S+U Lichtenberg/Siegfriedstr.',
      'Freiaplatz',
      'Guntherstr.',
      'Fanningerstr.',
      'Gotlindestr.',
      'Betriebshof Lichtenberg',
      'Siegfriedstr./Josef-Orlopp-Str.',
      'Herzbergstr./Siegfriedstr.',
      'Herzbergstr./Industriegebiet',
      'Bernhard-Bästlein-Str.',
      'Möllendorffstr./Storkower Str.',
      'Loeperplatz',
      'Scheffelstr./Paul-Junius-Str.',
      'James-Hobrecht-Str.',
      'Proskauer Str.',
      'Forckenbeckplatz',
      'Bersarinplatz',
      'U Frankfurter Tor',
      'Niederbarnimstr.',
      'Wismarplatz',
      'Boxhagener Str./Holteistr.',
      'Neue Bahnhofstr.',
      'Marktstr.',
      'S Rummelsburg',
      'Kosanke-Siedlung',
      'Gustav-Holzmann-Str.',
      'Heizkraftwerk',
      'Köpenicker Ch./Blockdammweg',
      'Blockdammweg/Ehrlichstr.',
      'Stechlinstr.',
      'Stühlinger Str.',
      'Treskowallee/Ehrlichstr.',
      'Hegemeisterweg',
      'Treskowallee/Volkspark Wuhlheide',
      'Rummelsburger Str./Edisonstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Brückenstr.',
      'S Schöneweide',
      'S Schöneweide/Sterndamm'
    ]
  },
  {
    line: '27',
    stops: [
      'Pasedagplatz',
      'Berliner Allee/Rennbahnstr.',
      'Falkenberger Str./Berliner Allee',
      'Buschallee',
      'Sulzfelder Str.',
      'Hansastr./Buschallee',
      'Stadion Buschallee/Suermondtstr.',
      'Degnerstr./Suermondtstr.',
      'Am Faulen See',
      'Alt-Hohenschönhausen',
      'Rhinstr./Gärtnerstr.',
      'Rhinstr./Plauener Str.',
      'Landsberger Allee/Rhinstr.',
      'Meeraner Str.',
      'Allee der Kosmonauten/Rhinstr.',
      'Kleingartenanlage Bielefeldt',
      'S Friedrichsfelde Ost',
      'Alt-Friedrichsfelde/Rhinstr.',
      'Am Tierpark/Alfred-Kowalke-Str.',
      'Criegernweg',
      'U Tierpark',
      'Treskowallee/HTW',
      'Marksburgstr.',
      'S Karlshorst',
      'S Karlshorst/Wandlitzstr.',
      'Treskowallee/ Ehrlichstr.',
      'Hegemeisterweg',
      'Treskowallee/Volkspark Wuhlheide',
      'Rummelsburger Str./Edisonstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Firlstr.',
      'Rathenaustr./HTW',
      'Ostendstr.',
      'Parkstr.',
      'Freizeit- und Erholungszentrum',
      'Nixenstr.',
      'Spindlersfelder Str.',
      'Alte Försterei',
      'Bahnhofstr./Lindenstr.',
      'Rathaus Köpenick',
      'Schloßplatz Köpenick',
      'Freiheit',
      'Müggelhm.Str./Wendenschloßstr.',
      'Pablo-Neruda-Str.',
      'Krkhs. Köpenick/Südseite'
    ]
  },
  {
    line: '37',
    stops: [
      'S+U Lichtenberg/Gudrunstr.',
      'S+U Lichtenberg/Siegfriedstr.',
      'Freiaplatz',
      'Guntherstr.',
      'Fanningerstr.',
      'Gotlindestr.',
      'Betriebshof Lichtenberg',
      'Siegfriedstr./Josef-Orlopp-Str.',
      'Herzbergstr./Siegfriedstr.',
      'Ev. Krankenhaus KEH',
      'Allee der Kosmonauten/Rhinstr.',
      'Kleingartenanlage Bielefeldt',
      'S Friedrichsfelde Ost',
      'Alt-Friedrichsfelde/Rhinstr.',
      'Am Tierpark/Alfred-Kowalke-Str.',
      'Criegernweg',
      'U Tierpark',
      'Treskowallee/HTW',
      'Marksburgstr.',
      'S Karlshorst',
      'S Karlshorst/Wandlitzstr.',
      'Treskowallee/ Ehrlichstr.',
      'Hegemeisterweg',
      'Treskowallee/Volkspark Wuhlheide',
      'Rummelsburger Str./Edisonstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Brückenstr.',
      'S Schöneweide',
      'S Schöneweide/Sterndamm'
    ]
  },
  {
    line: '50',
    stops: [
      'Guyotstr.',
      'Hugenottenplatz',
      'Arnouxstr.',
      'Navarraplatz',
      'Französisch Buchholz Kirche',
      'Blankenfelder Str.',
      'Rosenthaler Str.',
      'Marienstr./Pasewalker Str.',
      'Pasewalker Str/Blankenburger Weg',
      'Pankower Str.',
      'Galenusstr.',
      'S Pankow-Heinersdorf',
      'Würtzstr.',
      'Mendelstr.',
      'Stiftsweg',
      'Pankow Kirche',
      'S+U Pankow',
      'Masurenstr.',
      'U Vinetastr.',
      'Schönhauser Allee/Bornholmer Str',
      'Schönfließer Str.',
      'Björnsonstr.',
      'S Bornholmer Str.',
      'Grüntaler Str.',
      'Osloer Str./Prinzenallee',
      'Drontheimer Str.',
      'U Osloer Str.',
      'Louise-Schroeder-Platz',
      'Osram-Höfe',
      'U Seestr.',
      'Seestr./Amrumer Str.',
      'Virchow-Klinikum'
    ]
  },
  {
    line: '60',
    stops: [
      'Haeckelstr.',
      'Herweghstr.',
      'Mühlbergstr.',
      'Johannisthal Kirche',
      'Sterndamm/Königsheideweg',
      'Pietschkerstr.',
      'S Schöneweide/Sterndamm',
      'S Schöneweide',
      'Brückenstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Firlstr.',
      'Rathenaustr./HTW',
      'Ostendstr.',
      'Parkstr.',
      'Freizeit- und Erholungszentrum',
      'Nixenstr.',
      'Spindlersfelder Str.',
      'Alte Försterei',
      'Bahnhofstr./Lindenstr.',
      'Bahnhofstr./Seelenbinderstr.',
      'Gelnitzstr.',
      'Brandenburgplatz',
      'Bellevuestr.',
      'Hirschgarten',
      'Westendsiedlung',
      'Mühlweg',
      'Ahornallee',
      'S Friedrichshagen',
      'Drachholzstr.',
      'Marktplatz Friedrichshagen',
      'Müggelseedamm/Bölschestr.',
      'Josef-Nawrocki-Str.',
      'Bruno-Wille-Str.',
      'Altes Wasserwerk'
    ]
  },
  {
    line: '61',
    stops: [
      'Karl-Ziegler-Str.',
      'Magnusstr.',
      'Walther-Nernst-Str.',
      'S Adlershof',
      'Marktplatz Adlershof',
      'Wassermannstr.',
      'Ottomar-Geschke-Str.',
      'S Spindlersfeld',
      'Köllnischer Platz',
      'Schloßplatz Köpenick',
      'Freiheit',
      'Rathaus Köpenick',
      'Bahnhofstr./Lindenstr.',
      'Bahnhofstr./Seelenbinderstr.',
      'Gelnitzstr.',
      'Brandenburgplatz',
      'Bellevuestr.',
      'Hirschgarten',
      'Wassersportzentrum',
      'Spreestr.',
      'Müggelseedamm/Bölschestr.',
      'Marktplatz Friedrichshagen',
      'Drachholzstr.',
      'S Friedrichshagen',
      'Hartlebenstr.',
      'Wasserwerk Friedrichshagen',
      'Fürstenwalder Damm',
      'Fürstenwalder D/Müggelseedamm',
      'Licht- und Luftbad Müggelsee',
      'Strandbad Müggelsee',
      'Rahnsdorf/Waldschänke'
    ]
  },
  {
    line: '62',
    stops: [
      'Wendenschloß',
      'Müggelbergallee',
      'Lienhardweg',
      'Zur Nachtheide',
      'Dregerhoffstr.',
      'Pritstabelstr.',
      'Segewaldweg',
      'Mayschweg',
      'Betriebshof Köpenick',
      'Müggelhm.Str./Wendenschloßstr.',
      'Freiheit',
      'Schloßplatz Köpenick',
      'Rathaus Köpenick',
      'Bahnhofstr./Lindenstr.',
      'Bahnhofstr./Seelenbinderstr.',
      'S Köpenick',
      'Mahlsdorfer Str./Gehsener Str.',
      'Wongrowitzer Steig',
      'Unter den Birken',
      'Mahlsdorf-Süd',
      'Hultschiner Damm/Seestr.',
      'Roseggerstr.',
      'Erich-Baron-Weg',
      'Bütower Str.',
      'Bruchsaler Str.',
      'Eichenhofweg',
      'Ledebourstr.',
      'Rahnsdorfer Str.',
      'Alt-Mahlsdorf',
      'Wilhelmsmühlenweg',
      'S Mahlsdorf'
    ]
  },
  {
    line: '63',
    stops: [
      'Karl-Ziegler-Str.',
      'Magnusstr.',
      'Walther-Nernst-Str.',
      'S Adlershof',
      'Marktplatz Adlershof',
      'Wassermannstr.',
      'Ottomar-Geschke-Str.',
      'S Spindlersfeld',
      'Köllnischer Platz',
      'Schloßplatz Köpenick',
      'Freiheit',
      'Rathaus Köpenick',
      'Bahnhofstr./Lindenstr.',
      'Bahnhofstr./Seelenbinderstr.',
      'S Köpenick',
      'Mahlsdorfer Str./Gehsener Str.',
      'Wongrowitzer Steig',
      'Unter den Birken',
      'Mahlsdorf-Süd',
      'Hultschiner Damm/Seestr.',
      'Erich-Baron-Weg',
      'Bütower Str.',
      'Bruchsaler Str.',
      'Eichenhofweg',
      'Ledebourstr.',
      'Rahnsdorfer Str.'
    ]
  },
  {
    line: '67',
    stops: [
      'S Schöneweide/Sterndamm',
      'S Schöneweide',
      'Brückenstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Wilhelminenhofstr./Edisonstr.',
      'Firlstr.',
      'Rathenaustr./HTW',
      'Ostendstr.',
      'Parkstr.',
      'Freizeit- und Erholungszentrum',
      'Nixenstr.',
      'Spindlersfelder Str.',
      'Alte Försterei',
      'Bahnhofstr./Lindenstr.',
      'Rathaus Köpenick',
      'Schloßplatz Köpenick',
      'Freiheit',
      'Müggelhm.Str./Wendenschloßstr.',
      'Pablo-Neruda-Str.',
      'Krkhs. Köpenick/Südseite'
    ]
  },
  {
    line: '68',
    stops: [
      'Hirtestr.',
      'Hirtestr./Janitzkystr.',
      'S Köpenick',
      'S Köpenick',
      'Bahnhofstr./Seelenbinderstr.',
      'Bahnhofstr./Lindenstr.',
      'Rathaus Köpenick',
      'Freiheit',
      'Schloßplatz Köpenick',
      'Köllnischer Platz',
      'Glienicker Str.',
      'Vollkropfgraben',
      'Rosenweg',
      'Betonwerk',
      'Friedrich-Wolf-Str.',
      'Regattastr./Schule',
      'Wassersportallee',
      'S Grünau',
      'Regattatribünen',
      'Regattastr./Sportpromenade',
      'Strandbad Grünau',
      'Bammelecke',
      'Richtershorn',
      'Schappachstr.',
      'Lübbenauer Weg',
      'Adlergestell/Vetschauer Allee',
      'Zum Seeblick',
      'Alt-Schmöckwitz'
    ]
  }
];
