export interface UndergroundStop {
  line: string;
  stops: string[];
}

export const undergroundStops: UndergroundStop[] = [
  {
    line: 'U1',
    stops: [
      'S+U Warschauer Str.',
      'U Schlesisches Tor',
      'U Görlitzer Bahnhof',
      'U Kottbusser Tor',
      'U Prinzenstr.',
      'U Hallesches Tor',
      'U Möckernbrücke',
      'U Gleisdreieck',
      'U Kurfürstenstr.',
      'U Nollendorfplatz',
      'U Wittenbergplatz',
      'U Kurfürstendamm',
      'U Uhlandstr.'
    ]
  },
  {
    line: 'U2',
    stops: [
      'S+U Pankow',
      'U Vinetastr.',
      'S+U Schönhauser Allee',
      'U Eberswalder Str.',
      'U Senefelderplatz',
      'U Rosa-Luxemburg-Platz',
      'S+U Alexanderplatz',
      'U Klosterstr.',
      'U Märkisches Museum',
      'U Spittelmarkt',
      'U Hausvogteiplatz',
      'U Stadtmitte',
      'U Mohrenstr.',
      'S+U Potsdamer Platz',
      'U Mendelssohn-Bartholdy-Park',
      'U Gleisdreieck',
      'U Bülowstr.',
      'U Nollendorfplatz',
      'U Wittenbergplatz',
      'S+U Zoologischer Garten',
      'U Ernst-Reuter-Platz',
      'U Deutsche Oper',
      'U Bismarckstr.',
      'U Sophie-Charlotte-Platz',
      'U Kaiserdamm',
      'U Theodor-Heuss-Platz',
      'U Neu-Westend',
      'U Olympia-Stadion',
      'U Ruhleben'
    ]
  },
  {
    line: 'U3',
    stops: [
      'S+U Warschauer Str.',
      'U Schlesisches Tor',
      'U Görlitzer Bahnhof',
      'U Kottbusser Tor',
      'U Prinzenstr.',
      'U Hallesches Tor',
      'U Möckernbrücke',
      'U Gleisdreieck',
      'U Kurfürstenstr.',
      'U Nollendorfplatz',
      'U Wittenbergplatz',
      'U Augsburger Str.',
      'U Spichernstr.',
      'U Hohenzollernplatz',
      'U Fehrbelliner Platz',
      'S+U Heidelberger Platz',
      'U Rüdesheimer Platz',
      'U Breitenbachplatz',
      'U Podbielskiallee',
      'U Dahlem-Dorf',
      'U Freie Universität (Thielplatz)',
      'U Oskar-Helene-Heim',
      'U Onkel Toms Hütte',
      'U Krumme Lanke'
    ]
  },
  {
    line: 'U4',
    stops: [
      'U Nollendorfplatz',
      'U Viktoria-Luise-Platz',
      'U Bayerischer Platz',
      'U Rathaus Schöneberg',
      'S+U Innsbrucker Platz'
    ]
  },
  {
    line: 'U5',
    stops: [
      'U Hönow',
      'U Louis-Lewin-Str.',
      'U Hellersdorf',
      'U Cottbusser Platz',
      'U Kienberg (Gärten der Welt)',
      'U Kaulsdorf-Nord',
      'S+U Wuhletal',
      'U Elsterwerdaer Platz',
      'U Biesdorf-Süd',
      'U Tierpark',
      'U Friedrichsfelde',
      'S+U Lichtenberg',
      'U Magdalenenstr.',
      'S+U Frankfurter Allee',
      'U Samariterstr.',
      'U Frankfurter Tor',
      'U Weberwiese',
      'U Strausberger Platz',
      'U Schillingstr.',
      'S+U Alexanderplatz'
    ]
  },
  {
    line: 'U55',
    stops: [
      'S+U Brandenburger Tor',
      'U Bundestag',
      'S+U Hauptbahnhof'
    ]
  },
  {
    line: 'U6',
    stops: [
      'U Alt-Tegel',
      'U Borsigwerke',
      'U Holzhauser Str.',
      'U Otisstr.',
      'U Scharnweberstr.',
      'U Kurt-Schumacher-Platz',
      'U Afrikanische Str.',
      'U Rehberge',
      'U Seestr.',
      'U Leopoldplatz',
      'S+U Wedding',
      'U Reinickendorfer Str.',
      'U Schwartzkopffstr.',
      'U Naturkundemuseum',
      'U Oranienburger Tor',
      'S+U Friedrichstr.',
      'U Französische Str.',
      'U Stadtmitte',
      'U Kochstr./Checkpoint Charlie',
      'U Hallesches Tor',
      'U Mehringdamm',
      'U Platz der Luftbrücke',
      'U Paradestr.',
      'S+U Tempelhof',
      'U Alt-Tempelhof',
      'U Kaiserin-Augusta-Str.',
      'U Ullsteinstr.',
      'U Westphalweg',
      'U Alt-Mariendorf'
    ]
  },
  {
    line: 'U7',
    stops: [
      'S+U Rathaus Spandau',
      'U Altstadt Spandau',
      'U Zitadelle',
      'U Haselhorst',
      'U Paulsternstr.',
      'U Rohrdamm',
      'U Siemensdamm',
      'U Halemweg',
      'U Jakob-Kaiser-Platz',
      'S+U Jungfernheide',
      'U Mierendorffplatz',
      'U Richard-Wagner-Platz',
      'U Bismarckstr.',
      'U Wilmersdorfer Str.',
      'U Adenauerplatz',
      'U Konstanzer Str.',
      'U Fehrbelliner Platz',
      'U Blissestr.',
      'U Berliner Str.',
      'U Bayerischer Platz',
      'U Eisenacher Str.',
      'U Kleistpark',
      'S+U Yorckstr.',
      'U Möckernbrücke',
      'U Mehringdamm',
      'U Gneisenaustr.',
      'U Südstern',
      'U Hermannplatz',
      'U Rathaus Neukölln',
      'U Karl-Marx-Str.',
      'S+U Neukölln',
      'U Grenzallee',
      'U Blaschkoallee',
      'U Parchimer Allee',
      'U Britz-Süd',
      'U Johannisthaler Chaussee',
      'U Lipschitzallee',
      'U Wutzkyallee',
      'U Zwickauer Damm',
      'U Rudow'
    ]
  },
  {
    line: 'U8',
    stops: [
      'S+U Wittenau',
      'U Rathaus Reinickendorf',
      'S+U Karl-Bonhoeffer-Nervenklinik',
      'U Lindauer Allee',
      'U Paracelsus-Bad',
      'U Residenzstr.',
      'U Franz-Neumann-Platz',
      'U Osloer Str.',
      'U Pankstr.',
      'S+U Gesundbrunnen',
      'U Voltastr.',
      'U Bernauer Str.',
      'U Rosenthaler Platz',
      'U Weinmeisterstr.',
      'S+U Alexanderplatz',
      'S+U Jannowitzbrücke',
      'U Heinrich-Heine-Str.',
      'U Moritzplatz',
      'U Kottbusser Tor',
      'U Schönleinstr.',
      'U Hermannplatz',
      'U Boddinstr.',
      'U Leinestr.',
      'S+U Hermannstr.'
    ]
  },
  {
    line: 'U9',
    stops: [
      'U Osloer Str.',
      'U Nauener Platz',
      'U Leopoldplatz',
      'U Amrumer Str.',
      'S+U Westhafen',
      'U Birkenstr.',
      'U Turmstr.',
      'U Hansaplatz',
      'S+U Zoologischer Garten',
      'U Kurfürstendamm',
      'U Spichernstr.',
      'U Güntzelstr.',
      'U Berliner Str.',
      'S+U Bundesplatz',
      'U Friedrich-Wilhelm-Platz',
      'U Walther-Schreiber-Platz',
      'U Schloßstr.',
      'S+U Rathaus Steglitz'
    ]
  }
];
