name: BVG traffic information app pipeline

on:
  push:
    branches:
      - master

jobs:
  lint-build:
    name: Setup, lint and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm --prefix ./traffic-information-app install

      - name: Lint API specification
        uses: docker://openapitools/openapi-generator-cli
        with:
          args: validate -i api/spec.yaml

      - name: Lint application
        run: npm --prefix ./traffic-information-app run lint

      - name: Build application
        run: npm --prefix ./traffic-information-app run build
        env:
          BVG_API_KEY: ${{ secrets.BVG_API_KEY }}

      - name: Run tests
        run: npm --prefix ./traffic-information-app test -- --configuration=ci

#        The BVG 'dev' instance is not available enough to support this
#      - name: Run E2E tests
#        run: npm --prefix ./traffic-information-app run e2e -- --configuration=ci
